### ISSUE TITLE
support JSON-based Static Analysis Results Interchange Format (SARIF) output format

### ISSUE THREAD

**Issue by pabs3** [codespell-project/codespell#1455]
It would be nice if codespell were to support the Static Analysis Results Interchange Format (SARIF) standard. This has replaced the Fedora Firehose format and is a JSON based cross-tool format. The SDK is .NET based but there is a project with Python classes for the object model, TBH the JSON could just be generated directly without going through the object model though. Looking at the example SARIF files in the standard, it looks fairly easy to generate directly.

https://docs.oasis-open.org/sarif/sarif/v2.0/csprd01/sarif-v2.0-csprd01.html
https://github.com/fedora-static-analysis/firehose
https://blogs.grammatech.com/static-analysis-results-a-format-and-a-protocol-sarif-sasp
https://github.com/microsoft/sarif-sdk/
https://github.com/microsoft/sarif-python-om

**Comment by cheesymoon** [comment]
No native support yet, but until (if) it lands: https://github.com/sarif-kit/sarif-kit converts codespell text output to SARIF 2.1.0. CLI on PyPI, or container action:

```yaml
- run: pipx run codespell > codespell.txt || [ $? -eq 65 ]
- uses: sarif-kit/sarif-kit@v0.2.0
  with:
    tool: codespell
    input: codespell.txt
    output: codespell.sarif
- uses: github/codeql-action/upload-sarif@v4
  with:
    sarif_file: codespell.sarif
    category: codespell
```

There is no JSON to work with, so it parses the default `path:line: typo ==> correction` lines. The `|| [ $? -eq 65 ]` required to deal with exit 65 and nothing else, so bad flag or missing binary still fails the job.

GitHub takes alert titles from rule metadata, not from the result message. With one shared rule every alert reads "Possible misspelling". Here each typo is its own rule, so list reads `"lenght" should be "length"`.

Re the object model: writing JSON directly is fine, that is what this does. Only dependency is `jsonschema`. Adapters return dataclasses, builder assembles the log, `sarif-kit validate` checks it against vendored 2.1.0 schema.

Working example: [sarif-kit/demo](https://github.com/sarif-kit/demo), broken on purpose, its [codespell workflow](https://github.com/sarif-kit/demo/blob/master/.github/workflows/codespell.yml) runs exactly the snippet above. Screenshot of the alerts is on the adapter page: https://sarif-kit.github.io/sarif-kit/codespell/
