### ISSUE TITLE
How can I skip files when running codespell with pre-commit

### ISSUE THREAD

**Issue by johanvergeer** [codespell-project/codespell#1498]
It seems that skipping files isn't working when codespell is run with pre-commit.

Here is our `.pre-commit-config.yaml`:

```yaml
repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v1.16.0
    hooks:
      - id: codespell
        args: [--skip="*.json"]
```

We tried the following syntaxes for the args:

```yaml
args: ["--skip", "*.json"]
args: ["--skip=*.json"]
args: ["-S", "*.json"]
args: [-S, *.json]
args: [--skip=*.json]
args: [--skip="*.json"]
```

However, when we pass in an ignore file, that does seem to work

```yaml
repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v1.16.0
    hooks:
      - id: codespell
        args: [-I, .codespellignore]
```

Is it possible to ignore some files when running codespell with pre-commit?

**Comment by sergregory** [comment]
You can handle it with the pre-commit settings:
```yaml
  hooks:
      - id: codespell
        exclude: >
            (?x)^(
                .*\.json
            )$
```

Note that `(?x)^(` ... `)$` syntax is for multi-line comma-separated patterns, so you can exclude different groups of file in one hook

**Comment by johanvergeer** [comment]
Thanks for your fast reply @sergregory I have two more follow-up questions:

1. Where can I find the documentation on using codespell with pre-commit?
1. Would this be the correct syntax for ignoring multiple patterns, where I want to ignore all json and pyc files, and the entire `.tox` directory?

```yaml
  hooks:
      - id: codespell
        exclude: >
            (?x)^(
                .*\.json|.*\.pyc|\.tox
            )$
```

**Comment by sergregory** [comment]
@johanvergeer
1. Actually, I don't know - I was searching through the Internet on spellchecking the code, found this repo and your question :-)
2. Regarding the syntax - the variant that I've shown you is for *multi-line* regular expressions. It was designed to simplify the things and allow you to have different patterns in different lines. So yes, your variant is correct and you also can write it as follows:
```yaml
  hooks:
      - id: codespell
        exclude: >
            (?x)^(
                .*\.json|
                .*\.pyc|
                \.tox
            )$
```
Yoy can read more about it in pre-commit docs: https://pre-commit.com/#regular-expressions

**Comment by rkm** [comment]
Is there a reason the `args` key is ignored here? I'm seeing the same issue, but the `exclude` fix seems like a bit of a hack.

**Comment by sergregory** [comment]
@rkm try the sollution from the thread below - it looks reasonable for me
https://github.com/pre-commit/pre-commit/issues/971

**Comment by rkm** [comment]
I did some digging into how the pre-commit hook is called. Looks like the issue may be that even though a file is `--skip`ped, if it is explicitly listed in the files list afterwards then the `--skip` option is ignored:

```bash
$ codespell --skip foo.md -- foo.md
foo.md:1: fo ==> of, for
```

Is this the expected behavior for the `--skip` flag?

**Comment by rkm** [comment]
It seems like the `-x`/`--exclude-file` option could be used in the hook instead. This works for my use case (excluding a single file).

**Comment by johanvergeer** [comment]
I'm perfectly fine with the solution. if there is a better or more efficient way then I think it should be in another thread.

**Comment by peternewman** [comment]
> It seems like the `-x`/`--exclude-file` option could be used in the hook instead. This works for my use case (excluding a single file).

To clarify, the --exclude-file option is for a list of lines to ignore when running codespell. I agree the skip stuff is a bit odd, but as @rkm said that should be covered in #1528 .

**Comment by pytholic** [comment]
@johanvergeer You need to fix your quotes.

Wrong:
```yaml
repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v1.16.0
    hooks:
      - id: codespell
        args: [--skip="*.json"]
```

Correct:
```yaml
repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v1.16.0
    hooks:
      - id: codespell
        args: ["--skip=*.json"]
```
