### ISSUE TITLE
[bug] pyproject.toml cannot work in pre-commit-hook

### ISSUE THREAD

**Issue by Freed-Wu** [codespell-project/codespell#2530]
## Reproduce Steps

`a.vim`

```vim
nnoremap <C-W>e :enew<CR>
```

`pyproject.toml`

```toml
[tool.codespell]
ignore-words-list = "enew"
```

`.pre-commit-hook.yaml`

```yaml
---
repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
```

```sh
$ git init
$ pre-commit clean
$ git commit
codespell................................................................Failed
- hook id: codespell
- exit code: 65

a.vim:1: enew ==> new
pyproject.toml:2: enew ==> new
```

It seems something stop `pyproject.toml` to be read.

**Comment by Freed-Wu** [comment]
Oh, I found the reason:

```yaml
---
repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
```

I advice to add it to `README.md` to let more people know. :smile:
