### ISSUE TITLE
Advice on args in pre-commit don't appear to be working

### ISSUE THREAD

**Issue by Greedquest** [codespell-project/codespell#2723]
```yaml
repos:
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.2
  hooks:
  - id: codespell
    args: [--ignore-words-list iif]
```

My code contains `IIf` which is being corrected to `if`. The dictionary.txt contains lowercase `iif` so I'm trying to ignore that. What am I doing wrong here?

I'm using pre-commit in a github repo CI, not from desktop

**Comment by DimitriPapadopoulos** [comment]
Does it work from the command line? I am trying to understand if the question is about codespell itself, or about pre-commit.

**Comment by Greedquest** [comment]
Just checked, works from command line, not from pre-commit local or in CI

**Comment by DimitriPapadopoulos** [comment]
Then I guess it's a question of pre-commit syntax, not a codespell issue.

**Comment by Greedquest** [comment]
Oh my bad, should be
```diff
repos:
 - repo: https://github.com/codespell-project/codespell
   rev: v2.2.2
   hooks:
   - id: codespell
-    args: [--ignore-words-list iif]
+    args: [--ignore-words-list, iif]
```

with a comma

**Comment by DimitriPapadopoulos** [comment]
From the [.pre-commit-config.yaml](https://github.com/pypa/pip/blob/main/.pre-commit-config.yaml) file of codespell itself:
```yaml
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
        args: [--toml, pyproject-codespell.precommit-toml]
        additional_dependencies:
          - tomli
```
