### ISSUE TITLE
Docs request: how to put `check-filenames` and `ignore-words-list` into `pyproject.toml`

### ISSUE THREAD

**Issue by jamesbraza** [codespell-project/codespell#2839]
How can I put `check-filenames`, `check-hidden`, and `ignore-words-list` into `pyproject.toml`?

In the tests there doesn't seem to be a case for this: https://github.com/codespell-project/codespell/blob/v2.2.4/codespell_lib/tests/test_basic.py#L1028

From a GitHub Search, there's no results either: `tool.codespell filename:pyproject.toml`

And none of the below keys are working for me:

```toml
[tool.codespell]

check-filenames = true
check-hidden = true
ignore-words-list = ["acn"]
```

```
> codespell .
usage: codespell [-h] [--version] [-d] [-c] [-w] [-D DICTIONARY] [--builtin BUILTIN-LIST] [--ignore-regex IGNORE_REGEX] [-I FILE] [-L WORDS] [--uri-ignore-words-list WORDS] [-r REGEX] [--uri-regex URI_REGEX] [-s] [--count] [-S SKIP]
                 [-x FILE] [-i INTERACTIVE] [-q QUIET_LEVEL] [-e] [-f] [-H] [-A LINES] [-B LINES] [-C LINES] [--config CONFIG] [--toml TOML]
                 [files ...]
codespell: error: unrecognized arguments: True
```

From https://stackoverflow.com/questions/75377334/toml-how-to-have-key-without-value it seems keys without values aren't possible in `.toml`.

---

Related: https://github.com/codespell-project/codespell/issues/2718

Here is my old `.codespellrc`:

```rc
[codespell]
check-filenames =
check-hidden =
ignore-words-list = acn
```

**Comment by DimitriPapadopoulos** [comment]
`ignore-words-list` expects a “_comma separated list of words_”. Try:
```
ignore-words-list = 'acn'
```

**Comment by jamesbraza** [comment]
```toml
[tool.codespell]

ignore-words-list = "acn"
```

Works for me when invoking `codespell` from the command line or with this `pre-commit` config:

```yaml
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.4
  hooks:
  - id: codespell
    additional_dependencies:
      - tomli
```

---

How about `check-filenames` and `check-hidden`?

**Comment by rly** [comment]
> How about `check-filenames` and `check-hidden`?

Following the convention in https://github.com/codespell-project/codespell#using-a-config-file where `--count` in the command line corresponds to `count = ` in the `.codespellrc` file and `count = ''` in the `pyproject.toml` file, I tried this:

```toml
[tool.codespell]
ignore-words-list = "acn"
check-filenames = ""
check-hidden = ""
```

And it looks like it works as intended.

**Comment by DimitriPapadopoulos** [comment]
Shouldn't these work as well?
```toml
check-filenames = true
check-hidden = true
```
I wonder whether this should be considered a bug.

**Comment by DimitriPapadopoulos** [comment]
Not sure "correct" applies here, but yes, `true`/`false` should work now.

**Comment by DimitriPapadopoulos** [comment]
It could be implemented in TOML files, but the concept does not seem compatible with INI config files.

The difficulty is that our options processing model is based on command line options and INI config files. I have tried to add some flexibility to our parsing of TOML files, but such a change might be too complex here. The main difficulty difficulty might be that we need to remain compatible with 
[`argparse.ArgumentParser`](https://docs.python.org/3/library/argparse.html#argumentparser-objects) or rewrite the options parsing code.

Perhaps I can have a go at it when finalising #2767.

**Comment by Borda** [comment]
> The main difficulty difficulty might be that we need to remain compatible with [`argparse.ArgumentParser`](https://docs.python.org/3/library/argparse.html#argumentparser-objects)

yes I think just switching this options to accept one or more values with [nargs](https://docs.python.org/3/library/argparse.html#nargs) would be fully compatible and if only one is passed you try to split with comma

> or rewrite the entire options parsing code.

I would try [Fire](https://github.com/google/python-fire) which has zero additional dependencies; and eventually I can help

**Comment by Borda** [comment]
@DimitriPapadopoulos seems does not work for me...
```
docs/source/text/rouge_score.rst:2: ROUGE ==> ROGUE
docs/source/text/rouge_score.rst:9: ROUGE ==> ROGUE
docs/source/text/rouge_score.rst:15: rouge ==> rogue
docs/source/text/rouge_score.rst:21: rouge ==> rogue
...
```
with my `pyproject.toml` config
```toml
[tool.codespell]
# comma separated list of words
ignore-words-list = "ROUGE"
quiet-level = 3
```
and using precommit:
```yaml
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        additional_dependencies: [tomli]
```
