### ISSUE TITLE
`pre-commit` not respecting `--skip` for directory

### ISSUE THREAD

**Issue by jamesbraza** [codespell-project/codespell#3110]
I am running `codespell` via `pre-commit`:

```yaml
---
default_language_version:
    python: python3

repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        # TODO: use pyproject.toml config after release of https://github.com/codespell-project/codespell/issues/2839
        args:
          - --check-filenames
          - --check-hidden
          - --skip=./docs
```

It's currently not skipping my docs directory.  It works from command line, but not through `pre-commit`, regardless of quotes around `./docs`. Any ideas why this is happening?

I see lots of `--skip` issues, but I am using the proper/endorsed syntax of `./dirname`.

**Comment by jamesbraza** [comment]
(I discovered a workaround is using `pyproject.toml`, @DimitriPapadopoulos thoughts on cutting a new release?)

**Comment by jamesbraza** [comment]
Actually, even using `master` version for  a `pyproject.toml` config, the `docs/` still doesn't get respected.  Something about `pre-commit` is not playing nice with directory `skip`s

**Comment by DimitriPapadopoulos** [comment]
Indeed both should work from the command line: `--skip=docs` and `--skip=./docs`. Perhaps the working dir of pre-commit is not the one you think.

**Comment by DimitriPapadopoulos** [comment]
However, `--skip=docs` will always work.

**Comment by jamesbraza** [comment]
I am invoking `pre-commit` from the repo root and the entire `.pre-commit-config.yaml` is present in the OP.  Trying `--skip=docs` isn't working either, this is very strange to me.

https://github.com/jamesbraza/llama_index/tree/codespell is the fork, if you want to test this out, just run `pre-commit run --all-files`

**Comment by jamesbraza** [comment]
An aside is, any plans to cut a new release of `codespell` soon? 🤓 want to move to `pyproject.toml` after your `check-filenames` upgrade in https://github.com/codespell-project/codespell/issues/2839, without using `rev: master` in `pre-commit`

**Comment by DimitriPapadopoulos** [comment]
@larsoner Would you agree to a new codespell release?

**Comment by jamesbraza** [comment]
> Perhaps the working dir of pre-commit is not the one you think.

Even trying `repo: local` like so after `pip install codespell[toml]` installed doesn't work:

```yaml
---
default_language_version:
    python: python3

repos:
  - repo: local
    hooks:
      - id: codespell
        name: codespell
        entry: codespell
        language: python
        types: [text]
```

```toml
[tool.codespell]
skip = "docs"
```

**Comment by larsoner** [comment]
https://github.com/codespell-project/codespell/releases/tag/v2.2.6, should land on PyPI soon!

**Comment by jamesbraza** [comment]
Thanks both @larsoner and @DimitriPapadopoulos for your massive work here underlying that release! 👍

**Comment by jamesbraza** [comment]
Interestingly enough, after PR merge this issue went away.  It was something with how `pre-commit`, Git, and `codespell` interact.  @DimitriPapadopoulos you're right, it must have been some intricacy of `pre-commit`.

**Comment by paddyroddy** [comment]
I'm still having this issue with `v2.26`
```yaml
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        args:
          - --check-filenames
          - --check-hidden
          - --ignore-words-list=theses
          - --skip=.github/styles
```
The `.github/styles` isn't being ignored, none of `./.github/styles`, `.github` nor `styles` work either.

`- --skip=*bib` does work, which I also want.

**Comment by DimitriPapadopoulos** [comment]
It might be a different issue. First, `.github/styles` won't work. Then, pre-commit might run codespell on each file individually, instead of running codespell on the top-level directory as is usually the case. That might explain the issues you're experiencing, as codespell does not skip paths that are passed as explicit arguments (see #3196):
```
❯ mkdir -p .github/styles/subdir 1/2/.github/styles/subdir
❯ 
❯ echo theses > .github/styles/subdir/file
❯ echo theses > 1/2/.github/styles/subdir/file
❯ 
❯ codespell --check-hidden
./1/2/.github/styles/subdir/file:1: theses ==> these, thesis
./.github/styles/subdir/file:1: theses ==> these, thesis
❯ 
❯ codespell --check-hidden -S styles
❯ codespell --check-hidden -S .github
❯ codespell --check-hidden -S .github/styles
./1/2/.github/styles/subdir/file:1: theses ==> these, thesis
./.github/styles/subdir/file:1: theses ==> these, thesis
❯ 
❯ codespell --check-hidden -S styles 1
❯ codespell --check-hidden -S styles 1/2
❯ codespell --check-hidden -S styles 1/2/.github
❯ codespell --check-hidden -S styles 1/2/.github/styles
1/2/.github/styles/subdir/file:1: theses ==> these, thesis
❯ codespell --check-hidden -S styles 1/2/.github/styles/subdir
1/2/.github/styles/subdir/file:1: theses ==> these, thesis
❯ 
```
It would help if you could reproduce the issue from the command line.

**Comment by paddyroddy** [comment]
Sorry, the problem is I can't reproduce it on the CLI. Something like `codespell --ignore-words-list=theses --skip="*.bib,*.pdf,./.github/styles"` reports no errors. But yes, maybe `pre-commit` doesn't behave as I expect

**Comment by paddyroddy** [comment]
Not ideal but this would work
```yaml
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.6
  hooks:
    - id: codespell
      exclude: ^.github/styles
      exclude_types:
        - bib
      args:
        - --ignore-words-list=theses
```

**Comment by jamesbraza** [comment]
@paddyroddy I empathize with your struggles.  Since this issue was closed, I have repeatedly hit this `--skip` issue in several repos. I just figured I was having user error, but I think the truth is with `2.2.5` and `2.2.6`, there is a clear difference when invoking `codespell --skip=...` from the command line or `pre-commit`.

I have found when using `pyproject.toml` config or command line args:

- Multiple configurations of `--skip` work via direct command line usage
- Only exactly one configuration of `--skip` works via `pre-commit`
- I have also observed with a Git branch of `main` vs on the `main` branch affects things
    - This makes me think I am crazy, this observation definitely could be user error

When I hit this issue, I just try many possible `--skip` until I get one that works.

---

Here is my current `pre-commit` config that works:

```yaml
    - repo: https://github.com/codespell-project/codespell
      rev: v2.2.6
      hooks:
          - id: codespell
            additional_dependencies: [tomli]
```

And the associated `pyproject.toml` config:

```toml
[tool.codespell]
check-filenames = true
check-hidden = true
ignore-words-list = "astroid"
skip = "package-lock.json,storage/docstore.json,tests/cassettes/*"
```
