### ISSUE TITLE
codespell complains about its `ignore-words-list` in pyproject.toml

### ISSUE THREAD

**Issue by Borda** [codespell-project/codespell#3248]
Not sure if I am doing something wrong but found it confusing that Codepell is complaining about words from its own configuration... 

Running pre-commit with
```yaml
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        additional_dependencies: [tomli]
```
and having pyproject config
```toml
[tool.codespell]
skip = 'tests/*'
quiet-level = 3
ignore-words-list = "Chang,Manuel"
```
and getting the following error:
```
codespell................................................................Failed
- hook id: codespell
- exit code: 65

pyproject.toml:25: Manuel ==> Manual
```
found it while working on this PR: https://github.com/PyGithub/PyGithub/pull/2858
