### ISSUE TITLE
Codespell behaves differently in pre-commit when referencing files to exclude

### ISSUE THREAD

**Issue by jdholtz** [codespell-project/codespell#3306]
First of all, I love this project and have incorporated it into many of my own projects.

When ignoring files in my `pyproject.toml`, I reference a file using `./path/to/file`. When running `codespell` from the root directory of my project, this file is correctly ignored. However, when I run `pre-commit run --all-files`, the file is not ignored. When I change the file in my TOML config to `path/to/file` (note there is no `./` now), the pre-commit hook correctly ignores this, but running codespell in my root project directory now does not ignore this file. Below are the relevant files to reproduce this issue:

`utils/ignore.txt` (The file to ignore typos in):
```txt
typo in sentence: nNumber
```

`pyproject.toml`:
```toml
[tool.codespell]
skip = "utils/ignore.txt"
```

`.pre-commit-config.yaml`:
```
repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
```
