### ISSUE TITLE
Codespell Not Ignoring Words Properly when Provided in Original Case

### ISSUE THREAD

**Issue by SOHAN-cyber** [codespell-project/codespell#3385]
Codespell currently fails to properly ignore words if they are provided in their original case in the ignore file. For instance, when the word "OptIn" is added to the ignore file exactly as it is, Codespell does not recognize it as an ignored word during spell checks. However, when the word is added in lowercase, such as "optin", Codespell successfully ignores it as intended.

### Pre-commit Hook Config
```
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
        args:
          - --ignore-words=extern/make/.config/.codespellignore
          - --config=extern/make/.config/.codespell.toml
```

### .codespellignore
```
OptIn
```

## Error:
![CodeSpell Issue](https://github.com/codespell-project/codespell/assets/66588130/3e01780b-b8f2-4498-9463-02570f490521)

### Solution
To ensure Codespell ignores words correctly, users are currently required to add them in lowercase to the ignore file.

### Updated  .codespellignore File:

```
optin
```

You can find the proposed solution in the following link:

https://cobalt.googlesource.com/cobalt/+/master/.pre-commit-config.yaml#:~:text=%23%20The%20%2D%2Dignore%2Dwords,be%20lowercase%2C%20see
