### ISSUE TITLE
Unable to Ignore Files Completely Using .codespell.toml Configuration

### ISSUE THREAD

**Issue by Sohan-Opstree** [codespell-project/codespell#3446]
### Issue Description:
I have configured a .codespell.toml file to ignore certain files in my project, such as requirements.txt and *.csv. However, despite following the documentation, I'm unable to completely ignore the CHANGELOG.md file.

Steps to Reproduce:

Create a .codespell.toml file with the following configuration:
```
[tool.codespell]
skip = 'requirements.txt,*.csv,CHANGELOG.md'
```
Set up the pre-commit hook in the project's configuration:
## pre-commit hook:
```
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
        args:
          - --ignore-words=.config/.codespellignore
          - --config=.config/.codespell.toml
 ```

Run pre-commit run --all-files codespell.
Expected Behavior:
The CHANGELOG.md file should be completely ignored by codespell, as specified in the .codespell.toml configuration file.

### Actual Behavior:
The CHANGELOG.md file is not being ignored entirely, leading to errors during the codespell check.
```
pre-commit run --all-files codespell
codespell................................................................Failed
- hook id: codespell
- exit code: 65

CHANGELOG.md:253: re-declared ==> redeclared


```
