### ISSUE TITLE
Suggested `pre-commit` version is ancient

### ISSUE THREAD

**Issue by Jacobfaib** [codespell-project/codespell#3662]
The suggested pre-commit snippet in the README: https://github.com/codespell-project/codespell

> codespell also works with [pre-commit](https://pre-commit.com/), using

```yaml
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.4
  hooks:
  - id: codespell
```
is quite old. Suggest updating it to the latest version (2.4.1)
