### ISSUE TITLE
[tool.codespell] ignore-words-list ignored in Python 3.9 and 3.10

### ISSUE THREAD

**Issue by rvernica** [codespell-project/codespell#3684]
I have the following in _pyproject.toml_:
```
[tool.codespell]
ignore-words-list = ["iif", "DELETEing"]
```
In _.pre-commit-config.yaml_ I have:
```
  - repo: https://github.com/codespell-project/codespell
    rev: "v2.4.1"
    hooks:
      - id: codespell
```
This works fine when pre-commit is run on Python 3.11 to 3.13. On Python 3.9 and 3.10 I get:
```
codespell................................................................Failed
- hook id: codespell
- exit code: 65

pyproject.toml:50: iif ==> if
pyproject.toml:50: DELETEing ==> deleting
foo/bar.py:74: DELETEing ==> deleting
foo/taz.py:4: iif ==> if
```
